name: Deploy on Prod

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest changes
        run: |
          cd /home/lsei9899/public_html/expenses-api
          git pull origin prod
          php artisan migrate --force
          php artisan config:cache