name: Test SSH Access

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Test SSH connection
        run: ssh -p 2222 -o StrictHostKeyChecking=no lsei9899@yehezkellandau.com 'echo "SSH SUCCESS"'
